Repository dokuwiki/dokuwiki, pull requests merged in 2018-04, with the labels that each got.

#2241 PWA manifest and new @ini_theme_color replacement
  conf/manifest.json
  data/media/wiki/dokuwiki.svg
  inc/Manifest.php
  inc/StyleUtils.php
  inc/config_cascade.php
  inc/confutils.php
  inc/template.php
  lib/exe/css.php
  lib/exe/manifest.php
  lib/plugins/styling/admin.php
  lib/tpl/dokuwiki/lang/en/lang.php
  lib/tpl/dokuwiki/style.ini
Labels: ToDo: needDocUpdate

#2168 New CLI Plugin Type
  .gitignore
  bin/dwpage.php
  bin/gittool.php
  bin/indexer.php
  bin/plugin.php
  bin/render.php
  bin/striplangs.php
  bin/wantedpages.php
  composer.json
  composer.lock
  data/deleted.files
  inc/Plugin.php
  inc/PluginInterface.php
  inc/PluginTrait.php
  inc/cli.php
  inc/load.php
  inc/plugin.php
  inc/plugincontroller.class.php
  inc/pluginutils.php
  lib/plugins/cli.php
  vendor/composer/autoload_psr4.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
  vendor/splitbrain/php-cli/.gitignore
  vendor/splitbrain/php-cli/LICENSE
  vendor/splitbrain/php-cli/README.md
  vendor/splitbrain/php-cli/composer.json
  vendor/splitbrain/php-cli/src/CLI.php
  vendor/splitbrain/php-cli/src/Colors.php
  vendor/splitbrain/php-cli/src/Exception.php
  vendor/splitbrain/php-cli/src/Options.php
  vendor/splitbrain/php-cli/src/PSR3CLI.php
  vendor/splitbrain/php-cli/src/TableFormatter.php
Labels: ToDo: needDocUpdate

#2190 feat: canonically provide $ACT to javascript
  doku.php
  inc/common.php
  inc/template.php
  lib/exe/js.php
Labels: Needs Feedback/Discussion, ToDo: needDocUpdate

#2313 Prevent HTML and JS injection in section names
  _test/tests/inc/html_secedit_pattern.test.php
  inc/html.php
  inc/parser/xhtml.php
Labels: Bug, Security, Severity: Large

#2314 Fix invalid HTML
  inc/Form/ButtonElement.php
  inc/Ui/Search.php
  inc/Ui/SearchState.php
  lib/tpl/dokuwiki/css/_search.less
Labels: Bug, ToDo: needDocUpdate

#2354 unlock pages on viewing them
  inc/Action/Cancel.php
  inc/Action/Show.php
  inc/html.php
Labels: Bug
