Repository dokuwiki/dokuwiki, pull requests merged in 2025-01, with the labels that each got.

#4390 clientIP handling
  _test/tests/inc/Ip.test.php
  _test/tests/inc/common_clientip.test.php
  conf/dokuwiki.php
  inc/Ip.php
  inc/common.php
  lib/plugins/config/lang/en/lang.php
  lib/plugins/config/settings/config.metadata.php
Labels: ToDo: QuickMerge, ToDo: needDocUpdate

#3634 Add option 'modPassPlain' to send plaintext password updates to LDAP server
  lib/plugins/authldap/auth.php
  lib/plugins/authldap/conf/default.php
  lib/plugins/authldap/conf/metadata.php
  lib/plugins/authldap/lang/en/settings.php
Labels: Category: ACL & Authentication

#4389 use http_build_query() in buildURLparams()
  _test/tests/inc/parser/parser_media.test.php
  inc/common.php
Labels: ToDo: QuickMerge
